### ISSUE TITLE
Arch wiki link is empty

### ISSUE THREAD

**Issue by BoukeHaarsma23** [M1cha/archlinux-ostree#2]
The link in the readme seems to be pulled.

https://wiki.archlinux.org/title/Install_Arch_Linux_inside_OSTree

Could you just re-add it to the readme? Quite interested in this work :)

Thanks!

**Comment by M1cha** [comment]
It got moved to my user namespace because it's not an official guide, yet. I updated the link in the readme, but here it is: https://wiki.archlinux.org/title/User:M1cha/Install_Arch_Linux_inside_OSTree .

Feel free to let me know if you need any help or if you think, that parts of the guide need to be improved.
